"use client";
import Link from "next/link";
import { ArrowRight, FilePlus2, Sparkles } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useFormation } from "../../../lib/formation-context";
import { ProtocolBadge } from "../../../components/ui/ProtocolPrimitives";

const scenarios = [{ name: "Procurement agreement", title: "European provider intelligence report", text: "Produce a competitor report covering the five largest European providers, using public sources, by Friday at 17:00." }, { name: "Research / reporting", title: "Quarterly market brief", text: "Prepare a concise market brief with cited sources and deliver it by the end of the quarter." }, { name: "Freelance delivery", title: "Product launch package", text: "Deliver the launch package with design files, copy, and a review call within ten business days." }, { name: "Agent service", title: "Agent-to-agent service", text: "Monitor a service endpoint, report anomalies, and escalate verified incidents within one hour." }];
export default function NewAgreementPage() { const [title, setTitle] = useState(""); const [text, setText] = useState(""); const [a, setA] = useState("Atlas Procurement"); const [b, setB] = useState("Meridian Research"); const router = useRouter(); const { reset } = useFormation(); const load = (scenario: typeof scenarios[number]) => { setTitle(scenario.title); setText(scenario.text); }; return <div className="page"><div className="page-heading centered"><ProtocolBadge tone="violet">NEW AGREEMENT · V1</ProtocolBadge><h1>Start with shared meaning.</h1><p>Shape the agreement object, then send both interpretations through semantic review.</p></div><div className="wizard-grid"><form className="form-panel" onSubmit={event => { event.preventDefault(); reset(); router.push("/workspace"); }}><div className="form-field"><label htmlFor="title">AGREEMENT TITLE</label><input id="title" value={title} onChange={event => setTitle(event.target.value)} placeholder="e.g. European provider intelligence report" required /></div><div className="form-field"><label htmlFor="party-a">PARTY A</label><input id="party-a" value={a} onChange={event => setA(event.target.value)} /></div><div className="form-field"><label htmlFor="party-b">PARTY B</label><input id="party-b" value={b} onChange={event => setB(event.target.value)} /></div><div className="form-field"><label htmlFor="agreement-text">NATURAL LANGUAGE AGREEMENT</label><textarea id="agreement-text" value={text} onChange={event => setText(event.target.value)} placeholder="Describe the obligations both parties should understand…" required /></div><button className="button primary" type="submit"><FilePlus2 size={16} /> Create and open workspace <ArrowRight size={16} /></button></form><aside className="preview-panel"><ProtocolBadge tone="live"><Sparkles size={13} /> SCENARIO LOADER</ProtocolBadge><h2>Load a polished demo scenario</h2><p>Use a ready-made agreement to move directly into deterministic comparison.</p><div className="scenario-list">{scenarios.map(scenario => <button className="scenario-button" key={scenario.name} type="button" onClick={() => load(scenario)}>{scenario.name}<ArrowRight size={14} /></button>)}</div><Link className="text-link" href="/workspace">Continue with active demo <ArrowRight size={15} /></Link></aside></div></div>; }
