"use client";

import Link from "next/link";
import { ArrowRight, LoaderCircle, RefreshCw } from "lucide-react";
import { useFormation } from "../../lib/formation-context";
import { ConvergenceRail } from "../../components/semantic/ConvergenceRail";
import { HashDisplay, ProtocolBadge } from "../../components/ui/ProtocolPrimitives";

export default function ConsensusPage() {
  const { outcome, status, evaluationHash, evaluationHashStatus, verdictHash, tx, conflicts, evaluate, switchNetwork, evaluationReady, evaluationFinalized, stage, amend, agreementId, wallet, walletReady, walletChainId, notice } = useFormation();
  const submitting = status === "submitting";
  const statusText = submitting ? "Awaiting consensus" : outcome === "EQUIVALENT" ? "Shared meaning established" : outcome === "MATERIAL_CONFLICT" ? "Material conflict remains" : "Meaning has not been evaluated";
  const evaluateLabel = submitting ? "Submitting…" : evaluationFinalized ? "Verdict finalized" : evaluationHashStatus === "calculating" ? "Calculating hash…" : !wallet ? "Connect wallet to evaluate" : walletChainId !== null && !walletReady ? "Switch to Studio-dev" : "Evaluate meaning";
  const wrongNetwork = Boolean(wallet) && walletChainId !== null && !walletReady;
  const actionDisabled = submitting || evaluationHashStatus === "calculating" || (!wrongNetwork && !evaluationReady);
  return <div className="page consensus-page">
    <div className="page-heading centered"><ProtocolBadge tone="violet">CONSENSUS ENGINE · GENLAYER</ProtocolBadge><h1>Judgment, made visible.</h1><p>Deterministic signals meet validator reasoning at the semantic node.</p></div>
    <section className="consensus-stage"><ConvergenceRail large /><div className={`consensus-core ${submitting ? "processing" : ""} ${outcome.toLowerCase()}`}><div className="core-rings" /><span>{submitting ? <LoaderCircle className="spin" size={24} /> : "GL"}</span><strong>GENLAYER</strong><small>SEMANTIC CONSENSUS</small></div><div className="status-orbit"><ProtocolBadge tone={submitting ? "violet" : outcome === "EQUIVALENT" ? "success" : outcome === "MATERIAL_CONFLICT" ? "conflict" : "neutral"}>{statusText}</ProtocolBadge><p>{submitting ? "Preparing semantic input · Submitting to validators · Awaiting consensus · Finalizing judgment" : "The animation reflects lifecycle state; the outcome below is read from the real transaction."}</p></div></section>
    <section className="consensus-data"><div><small>INPUT HASH</small><HashDisplay value={evaluationHash} status={evaluationHashStatus} compact /></div><div><small>VERDICT HASH</small><HashDisplay label="VERDICT" value={verdictHash} status={verdictHash ? "ready" : "idle"} emptyText={submitting ? "Awaiting finalization" : "No finalized verdict"} compact /></div><div><small>TRANSACTION</small><HashDisplay label="TX" value={tx} status={tx ? "ready" : "idle"} emptyText={submitting ? "Submitting transaction" : "Not submitted"} compact /></div><div><small>DETERMINISTIC CHECK</small><strong className={conflicts.length ? "coral" : "mint"}>{conflicts.length ? conflicts.join(" · ") : "No conflicts"}</strong></div></section>
    {notice && <p className="protocol-notice" role="status">{notice}</p>}
    <details className="inspector"><summary>Open consensus inspector</summary><div className="inspector-grid"><div><small>AGREEMENT ID</small><strong>{agreementId}</strong></div><div><small>NETWORK</small><strong>Studio-dev · 61997</strong></div><div><small>WALLET</small><strong>{wallet ? `${wallet.slice(0, 8)}…${wallet.slice(-6)}` : "Not connected"}</strong></div><div><small>VERDICT</small><strong>{outcome}</strong></div><div><small>EVALUATION HASH</small><strong>{evaluationHash || "Not ready"}</strong></div><div><small>CONTRACT</small><strong>{process.env.NEXT_PUBLIC_GENLAYER_CONTRACT_ADDRESS || "Configured at deploy"}</strong></div><div><small>TRANSACTION</small><strong>{tx || "Not submitted"}</strong></div></div></details>
    <section className="consensus-actions">{stage === "conflict" && <button className="button ghost" onClick={amend} disabled={submitting} title={submitting ? "Wait for the current evaluation to finish." : "Apply the guided demo amendment."}><RefreshCw size={16} />Apply demo amendment</button>}<button className="button primary" onClick={() => void (wrongNetwork ? switchNetwork() : evaluate())} disabled={actionDisabled} title={wrongNetwork ? "Switch the connected wallet to Studio-dev · 61997." : !evaluationReady ? (evaluationFinalized ? "Apply an amendment to create a new semantic input." : "Connect a Studio-dev wallet and wait for the semantic hash to be ready.") : undefined}>{evaluateLabel}<ArrowRight size={16} /></button>{outcome === "EQUIVALENT" && evaluationFinalized && <Link className="button subtle" href="/ratification">Continue to ratification <ArrowRight size={16} /></Link>}</section>
  </div>;
}
