"use client";

import { CheckCircle2, Search, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { useFormation } from "../../lib/formation-context";
import { isFormationReceiptConsistent } from "../../lib/formation";
import { ExplorerLink, HashDisplay, ProtocolBadge } from "../../components/ui/ProtocolPrimitives";

export default function VerifyPage() {
  const { receipt, agreementId, model, canonicalHash, evaluationHash, verdictHash, tx, authoritativeRead, refreshAuthoritativeState } = useFormation();
  const [query, setQuery] = useState("");
  const [checked, setChecked] = useState(false);
  const receiptConsistent = isFormationReceiptConsistent(receipt, { agreementId, canonicalHash, evaluationHash, verdictHash, transactionHash: tx, contractAddress: process.env.NEXT_PUBLIC_GENLAYER_CONTRACT_ADDRESS || "", network: "Studio-dev", policyVersion: model.policyVersion });
  const valid = receiptConsistent && (!query || query === receipt.agreementId || query === receipt.canonicalAgreementHash || query === receipt.transactionHash);
  return <div className="page"><div className="page-heading centered"><ProtocolBadge tone="live">PROOF VERIFICATION</ProtocolBadge><h1>Verify the meaning.</h1><p>Inspect a Formation Receipt or read the current negotiation state directly from the Intelligent Contract.</p></div><section className="verify-panel"><div className="form-field"><label htmlFor="proof-query">RECEIPT ID OR HASH</label><input id="proof-query" value={query} onChange={event => { setQuery(event.target.value); setChecked(false); }} placeholder="AG-… or sha256…" /></div><div className="verify-actions"><button className="button primary" onClick={() => setChecked(true)}><Search size={16} /> Check local receipt</button><button className="button subtle" onClick={() => void refreshAuthoritativeState()}><Search size={16} /> Read contract state</button></div>{authoritativeRead && <div className="verify-result"><ProtocolBadge tone="live">INTELLIGENT CONTRACT · FRESH READ</ProtocolBadge><h2>{authoritativeRead.state}</h2><p>Read at {new Date(authoritativeRead.readAt).toLocaleString()}. This is authoritative network state, separate from the browser receipt.</p><HashDisplay label="CONTRACT CANONICAL HASH" value={authoritativeRead.canonicalHash} compact /><HashDisplay label="CONTRACT VERDICT" value={authoritativeRead.verdict} compact /></div>}{checked && <div className={`verify-result ${valid ? "" : "invalid"}`}>{valid ? <><CheckCircle2 size={22} className="mint" /><ProtocolBadge tone="success">LOCAL RECEIPT · MATCHED</ProtocolBadge><h2>Receipt matches this session.</h2><p>This browser receipt is internally consistent with the current canonical hash, ratifications, verdict, and transaction. Use “Read contract state” above for a fresh Intelligent Contract readback.</p><HashDisplay label="CANONICAL HASH" value={receipt.canonicalAgreementHash} compact /><HashDisplay label="TRANSACTION" value={receipt.transactionHash} compact /><div className="verify-links"><ExplorerLink value={receipt.transactionHash} /><ExplorerLink kind="address" value={receipt.contractAddress} /></div></> : <><ShieldAlert size={22} className="coral" /><h2>No matching local receipt</h2><p>Complete semantic consensus and matching ratification in this browser session, then check the resulting agreement ID, canonical hash, or transaction.</p></>}</div>}</section></div>;
}
